/********************************************************************************
** Form generated from reading UI file 'keyboard.ui'
**
** Created by: Qt User Interface Compiler version 4.8.5
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_KEYBOARD_H
#define UI_KEYBOARD_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QDialog>
#include <QtGui/QHeaderView>
#include <QtGui/QLCDNumber>
#include <QtGui/QLineEdit>
#include <QtGui/QSlider>
#include <QtGui/QToolButton>
//#define KEYBOARD_W  30
//#define KETBOARD_H  25
#define KEYBOARD_W  20
#define KETBOARD_H  19
//#define KEYBOARDLENTH_H 670
//#define KEYBOARDLENTH_W 326
#define KEYBOARDLENTH_H 480
#define KEYBOARDLENTH_W 272

QT_BEGIN_NAMESPACE

class Ui_KeyBoard
{
public:
    QToolButton *toolButton_l;
    QLCDNumber *lcdNumber;
    QToolButton *toolButton_line2;
    QToolButton *toolButton_line1;
    QToolButton *toolButton_m;
    QToolButton *toolButton_right;
    QToolButton *toolButton_j;
    QToolButton *toolButton_k;
    QToolButton *toolButton_h;
    QToolButton *toolButton_9;
    QToolButton *toolButton_r;
    QToolButton *toolButton_8;
    QToolButton *toolButton_t;
    QToolButton *toolButton_7;
    QToolButton *toolButton_u;
    QToolButton *toolButton_d;
    QToolButton *toolButton_3;
    QToolButton *toolButton_tab;
    QToolButton *toolButton_6;
    QToolButton *toolButton_y;
    QToolButton *toolButton_dot;
    QToolButton *toolButton_g;
    QToolButton *toolButton_i;
    QToolButton *toolButton_s;
    QToolButton *toolButton_o;
    QToolButton *toolButton_w;
    QToolButton *toolButton_a;
    QLineEdit *display;
    QToolButton *toolButton_capslock;
    QToolButton *toolButton_b;
    QToolButton *toolButton_left;
    QToolButton *toolButton_n;
    QToolButton *toolButton_c;
    QToolButton *toolButton_x;
    QToolButton *toolButton_up;
    QToolButton *toolButton_backspace;
    QToolButton *toolButton_5;
    QToolButton *toolButton_v;
    QToolButton *toolButton_esc;
    QToolButton *toolButton_enter;
    QToolButton *toolButton_p;
    QToolButton *toolButton_down;
    QToolButton *toolButton_4;
    QToolButton *toolButton_q;
    QToolButton *toolButton_0;
    QToolButton *toolButton_f;
    QToolButton *toolButton_space;
    QToolButton *toolButton_wenhao;
    QToolButton *toolButton_e;
    QSlider *horizontalSlider;
    QToolButton *toolButton_2;
    QToolButton *toolButton_1;
    QToolButton *toolButton_z;
    QToolButton *toolButton_Inv;
    QToolButton *toolButton_line3;

    void setupUi(QDialog *KeyBoard)
    {
        if (KeyBoard->objectName().isEmpty())
            KeyBoard->setObjectName(QString::fromUtf8("KeyBoard"));
        //KeyBoard->resize(375, 150);
        KeyBoard->resize(KEYBOARDLENTH_H, KEYBOARDLENTH_W);
        toolButton_l = new QToolButton(KeyBoard);
        toolButton_l->setObjectName(QString::fromUtf8("toolButton_l"));
        //toolButton_l->setGeometry(QRect(303+10*KETBOARD_H, 76+3*KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_l->setGeometry(QRect(197+10*KETBOARD_H, 57+3*KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(toolButton_l->sizePolicy().hasHeightForWidth());
        toolButton_l->setSizePolicy(sizePolicy);
        toolButton_l->setFocusPolicy(Qt::NoFocus);
        lcdNumber = new QLCDNumber(KeyBoard);
        lcdNumber->setObjectName(QString::fromUtf8("lcdNumber"));
//        lcdNumber->setGeometry(QRect(10, 101+4*KEYBOARD_W, 47+KETBOARD_H, 23+KEYBOARD_W));
        lcdNumber->setGeometry(QRect(6, 76+4*KEYBOARD_W, 31+KETBOARD_H, 17+KEYBOARD_W));
        lcdNumber->setFrameShape(QFrame::StyledPanel);
        lcdNumber->setFrameShadow(QFrame::Plain);
        lcdNumber->setSegmentStyle(QLCDNumber::Flat);
        lcdNumber->setProperty("value", QVariant(255));
        lcdNumber->setStyleSheet("background-color:rgb(199,237,204)");
        toolButton_line2 = new QToolButton(KeyBoard);
        toolButton_line2->setObjectName(QString::fromUtf8("toolButton_line2"));
        toolButton_line2->setStyleSheet("background-color:rgb(199,237,204)");
        //toolButton_line2->setGeometry(QRect(332+11*KETBOARD_H, 76+3*KEYBOARD_W, 37+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_line2->setGeometry(QRect(216+11*KETBOARD_H, 57+3*KEYBOARD_W, 24+KETBOARD_H, 19+KEYBOARD_W));
        toolButton_line1 = new QToolButton(KeyBoard);
        toolButton_line1->setObjectName(QString::fromUtf8("toolButton_line1"));
        toolButton_line1->setStyleSheet("background-color:rgb(199,237,204)");
//        toolButton_line1->setGeometry(QRect(9, 75+3*KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_line1->setGeometry(QRect(5,57+3*KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        toolButton_m = new QToolButton(KeyBoard);
        toolButton_m->setObjectName(QString::fromUtf8("toolButton_m"));
//        toolButton_m->setGeometry(QRect(265+8*KETBOARD_H, 101+4*KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_m->setGeometry(QRect(172+8*KETBOARD_H, 76+4*KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_m->sizePolicy().hasHeightForWidth());
        toolButton_m->setSizePolicy(sizePolicy);
        toolButton_m->setFocusPolicy(Qt::NoFocus);
        toolButton_right = new QToolButton(KeyBoard);
        toolButton_right->setObjectName(QString::fromUtf8("toolButton_right"));
//        toolButton_right->setGeometry(QRect(332+10*KETBOARD_H, 126+5*KEYBOARD_W, 38+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_right->setGeometry(QRect(216+10*KETBOARD_H, 95+5*KEYBOARD_W, 24+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_right->sizePolicy().hasHeightForWidth());
        toolButton_right->setSizePolicy(sizePolicy);
        toolButton_right->setFocusPolicy(Qt::NoFocus);
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/new/keypad/picture/keypad/right.png"), QSize(), QIcon::Normal, QIcon::Off);
        toolButton_right->setIcon(icon);
        toolButton_j = new QToolButton(KeyBoard);
        toolButton_j->setObjectName(QString::fromUtf8("toolButton_j"));
//        toolButton_j->setGeometry(QRect(244+8*KETBOARD_H, 76+3*KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_j->setGeometry(QRect(158+8*KETBOARD_H, 57+3*KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_j->sizePolicy().hasHeightForWidth());
        toolButton_j->setSizePolicy(sizePolicy);
        toolButton_j->setFocusPolicy(Qt::NoFocus);
        toolButton_k = new QToolButton(KeyBoard);
        toolButton_k->setObjectName(QString::fromUtf8("toolButton_k"));
//        toolButton_k->setGeometry(QRect(273+9*KETBOARD_H, 76+3*KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
         toolButton_k->setGeometry(QRect(178+9*KETBOARD_H, 57+3*KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_k->sizePolicy().hasHeightForWidth());
        toolButton_k->setSizePolicy(sizePolicy);
        toolButton_k->setFocusPolicy(Qt::NoFocus);
        toolButton_h = new QToolButton(KeyBoard);
        toolButton_h->setObjectName(QString::fromUtf8("toolButton_h"));
//        toolButton_h->setGeometry(QRect(215+7*KETBOARD_H, 76+3*KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_h->setGeometry(QRect(139+7*KETBOARD_H, 57+3*KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_h->sizePolicy().hasHeightForWidth());
        toolButton_h->setSizePolicy(sizePolicy);
        toolButton_h->setFocusPolicy(Qt::NoFocus);
        toolButton_9 = new QToolButton(KeyBoard);
        toolButton_9->setObjectName(QString::fromUtf8("toolButton_9"));
//        toolButton_9->setGeometry(QRect(280+9*KETBOARD_H, 26+KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_9->setGeometry(QRect(182+9*KETBOARD_H, 20+KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_9->sizePolicy().hasHeightForWidth());
        toolButton_9->setSizePolicy(sizePolicy);
        toolButton_9->setFocusPolicy(Qt::NoFocus);
        toolButton_r = new QToolButton(KeyBoard);
        toolButton_r->setObjectName(QString::fromUtf8("toolButton_r"));
//        toolButton_r->setGeometry(QRect(142+4*KETBOARD_H, 51+2*KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_r->setGeometry(QRect(92+4*KETBOARD_H, 39+2*KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_r->sizePolicy().hasHeightForWidth());
        toolButton_r->setSizePolicy(sizePolicy);
        toolButton_r->setFocusPolicy(Qt::NoFocus);
        toolButton_8 = new QToolButton(KeyBoard);
        toolButton_8->setObjectName(QString::fromUtf8("toolButton_8"));
//        toolButton_8->setGeometry(QRect(251+8*KETBOARD_H, 26+KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_8->setGeometry(QRect(163+8*KETBOARD_H, 20+KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_8->sizePolicy().hasHeightForWidth());
        toolButton_8->setSizePolicy(sizePolicy);
        toolButton_8->setFocusPolicy(Qt::NoFocus);
        toolButton_t = new QToolButton(KeyBoard);
        toolButton_t->setObjectName(QString::fromUtf8("toolButton_t"));
//        toolButton_t->setGeometry(QRect(171+5*KETBOARD_H, 51+2*KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_t->setGeometry(QRect(111+5*KETBOARD_H, 39+2*KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_t->sizePolicy().hasHeightForWidth());
        toolButton_t->setSizePolicy(sizePolicy);
        toolButton_t->setFocusPolicy(Qt::NoFocus);
        toolButton_7 = new QToolButton(KeyBoard);
        toolButton_7->setObjectName(QString::fromUtf8("toolButton_7"));
//        toolButton_7->setGeometry(QRect(222+7*KETBOARD_H, 26+KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_7->setGeometry(QRect(144+7*KETBOARD_H, 20+KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_7->sizePolicy().hasHeightForWidth());
        toolButton_7->setSizePolicy(sizePolicy);
        toolButton_7->setFocusPolicy(Qt::NoFocus);
        toolButton_u = new QToolButton(KeyBoard);
        toolButton_u->setObjectName(QString::fromUtf8("toolButton_u"));
//        toolButton_u->setGeometry(QRect(227+7*KETBOARD_H, 51+2*KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_u->setGeometry(QRect(148+7*KETBOARD_H, 39+2*KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_u->sizePolicy().hasHeightForWidth());
        toolButton_u->setSizePolicy(sizePolicy);
        toolButton_u->setFocusPolicy(Qt::NoFocus);
        toolButton_d = new QToolButton(KeyBoard);
        toolButton_d->setObjectName(QString::fromUtf8("toolButton_d"));
//        toolButton_d->setGeometry(QRect(129+4*KETBOARD_H, 76+3*KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_d->setGeometry(QRect(83+4*KETBOARD_H, 57+3*KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_d->sizePolicy().hasHeightForWidth());
        toolButton_d->setSizePolicy(sizePolicy);
        toolButton_d->setFocusPolicy(Qt::NoFocus);
        toolButton_3 = new QToolButton(KeyBoard);
        toolButton_3->setObjectName(QString::fromUtf8("toolButton_3"));
//        toolButton_3->setGeometry(QRect(105+3*KETBOARD_H, 26+KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_3->setGeometry(QRect(68+3*KETBOARD_H, 20+KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_3->sizePolicy().hasHeightForWidth());
        toolButton_3->setSizePolicy(sizePolicy);
        toolButton_3->setFocusPolicy(Qt::NoFocus);
        toolButton_tab = new QToolButton(KeyBoard);
        toolButton_tab->setObjectName(QString::fromUtf8("toolButton_tab"));
        toolButton_tab->setStyleSheet("background-color:rgb(199,237,204)");
//        toolButton_tab->setGeometry(QRect(8, 26+KEYBOARD_W, 63, 25+KEYBOARD_W));
        toolButton_tab->setGeometry(QRect(5, 20+KEYBOARD_W, 41, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_tab->sizePolicy().hasHeightForWidth());
        toolButton_tab->setSizePolicy(sizePolicy);
        toolButton_tab->setFocusPolicy(Qt::NoFocus);
        toolButton_6 = new QToolButton(KeyBoard);
        toolButton_6->setObjectName(QString::fromUtf8("toolButton_6"));
//        toolButton_6->setGeometry(QRect(193+6*KETBOARD_H, 26+KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_6->setGeometry(QRect(125+6*KETBOARD_H, 20+KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_6->sizePolicy().hasHeightForWidth());
        toolButton_6->setSizePolicy(sizePolicy);
        toolButton_6->setFocusPolicy(Qt::NoFocus);
        toolButton_y = new QToolButton(KeyBoard);
        toolButton_y->setObjectName(QString::fromUtf8("toolButton_y"));
//        toolButton_y->setGeometry(QRect(199+6*KETBOARD_H, 51+2*KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_y->setGeometry(QRect(130+6*KETBOARD_H, 39+2*KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_y->sizePolicy().hasHeightForWidth());
        toolButton_y->setSizePolicy(sizePolicy);
        toolButton_y->setFocusPolicy(Qt::NoFocus);
        toolButton_dot = new QToolButton(KeyBoard);
        toolButton_dot->setObjectName(QString::fromUtf8("toolButton_dot"));
//        toolButton_dot->setGeometry(QRect(342+11*KETBOARD_H, 51+2*KEYBOARD_W, 26+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_dot->setGeometry(QRect(222+11*KETBOARD_H, 39+2*KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        toolButton_dot->setStyleSheet("background-color:rgb(199,237,204)");
        sizePolicy.setHeightForWidth(toolButton_dot->sizePolicy().hasHeightForWidth());
        toolButton_dot->setSizePolicy(sizePolicy);
        toolButton_dot->setFocusPolicy(Qt::NoFocus);
        toolButton_g = new QToolButton(KeyBoard);
        toolButton_g->setObjectName(QString::fromUtf8("toolButton_g"));
//        toolButton_g->setGeometry(QRect(186+6*KETBOARD_H, 76+3*KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_g->setGeometry(QRect(120+6*KETBOARD_H, 57+3*KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_g->sizePolicy().hasHeightForWidth());
        toolButton_g->setSizePolicy(sizePolicy);
        toolButton_g->setFocusPolicy(Qt::NoFocus);
        toolButton_i = new QToolButton(KeyBoard);
        toolButton_i->setObjectName(QString::fromUtf8("toolButton_i"));
//        toolButton_i->setGeometry(QRect(256+8*KETBOARD_H, 51+2*KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_i->setGeometry(QRect(166+8*KETBOARD_H, 39+2*KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_i->sizePolicy().hasHeightForWidth());
        toolButton_i->setSizePolicy(sizePolicy);
        toolButton_i->setFocusPolicy(Qt::NoFocus);
        toolButton_s = new QToolButton(KeyBoard);
        toolButton_s->setObjectName(QString::fromUtf8("toolButton_s"));
//        toolButton_s->setGeometry(QRect(100+3*KETBOARD_H, 76+3*KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_s->setGeometry(QRect(65+3*KETBOARD_H, 57+3*KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_s->sizePolicy().hasHeightForWidth());
        toolButton_s->setSizePolicy(sizePolicy);
        toolButton_s->setFocusPolicy(Qt::NoFocus);
        toolButton_o = new QToolButton(KeyBoard);
        toolButton_o->setObjectName(QString::fromUtf8("toolButton_o"));
//        toolButton_o->setGeometry(QRect(284+9*KETBOARD_H, 51+2*KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_o->setGeometry(QRect(184+9*KETBOARD_H, 39+2*KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_o->sizePolicy().hasHeightForWidth());
        toolButton_o->setSizePolicy(sizePolicy);
        toolButton_o->setFocusPolicy(Qt::NoFocus);
        toolButton_w = new QToolButton(KeyBoard);
        toolButton_w->setObjectName(QString::fromUtf8("toolButton_w"));
//        toolButton_w->setGeometry(QRect(83+2*KETBOARD_H, 51+2*KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_w->setGeometry(QRect(53+2*KETBOARD_H, 39+2*KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_w->sizePolicy().hasHeightForWidth());
        toolButton_w->setSizePolicy(sizePolicy);
        toolButton_w->setFocusPolicy(Qt::NoFocus);
        toolButton_a = new QToolButton(KeyBoard);
        toolButton_a->setObjectName(QString::fromUtf8("toolButton_a"));
//        toolButton_a->setGeometry(QRect(71+2*KETBOARD_H, 76+3*KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_a->setGeometry(QRect(46+2*KETBOARD_H, 57+3*KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_a->sizePolicy().hasHeightForWidth());
        toolButton_a->setSizePolicy(sizePolicy);
        toolButton_a->setFocusPolicy(Qt::NoFocus);
        display = new QLineEdit(KeyBoard);
        display->setObjectName(QString::fromUtf8("display"));
//        display->setGeometry(QRect(46+KETBOARD_H, -1, 238+3*KETBOARD_H, 27+KEYBOARD_W));
        display->setGeometry(QRect(30+KETBOARD_H, -1, 155+3*KETBOARD_H, 21+KEYBOARD_W));
        display->setStyleSheet("background-color:rgb(199,237,204)");
        toolButton_capslock = new QToolButton(KeyBoard);
        toolButton_capslock->setObjectName(QString::fromUtf8("toolButton_capslock"));
        toolButton_capslock->setStyleSheet("background-color:rgb(199,237,204)");
//        toolButton_capslock->setGeometry(QRect(8, 50+2*KEYBOARD_W, 45+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_capslock->setGeometry(QRect(5, 38+2*KEYBOARD_W, 29+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_capslock->sizePolicy().hasHeightForWidth());
        toolButton_capslock->setSizePolicy(sizePolicy);
        toolButton_capslock->setFocusPolicy(Qt::NoFocus);
        toolButton_b = new QToolButton(KeyBoard);
        toolButton_b->setObjectName(QString::fromUtf8("toolButton_b"));
//        toolButton_b->setGeometry(QRect(207+6*KETBOARD_H, 101+4*KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_b->setGeometry(QRect(134+6*KETBOARD_H, 76+4*KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_b->sizePolicy().hasHeightForWidth());
        toolButton_b->setSizePolicy(sizePolicy);
        toolButton_b->setFocusPolicy(Qt::NoFocus);
        toolButton_left = new QToolButton(KeyBoard);
        toolButton_left->setObjectName(QString::fromUtf8("toolButton_left"));
//        toolButton_left->setGeometry(QRect(256+8*KETBOARD_H, 126+5*KEYBOARD_W, 38+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_left->setGeometry(QRect(166+8*KETBOARD_H, 95+5*KEYBOARD_W, 24+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_left->sizePolicy().hasHeightForWidth());
        toolButton_left->setSizePolicy(sizePolicy);
        toolButton_left->setFocusPolicy(Qt::NoFocus);
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/new/keypad/picture/keypad/left.png"), QSize(), QIcon::Normal, QIcon::Off);
        toolButton_left->setIcon(icon1);
        toolButton_n = new QToolButton(KeyBoard);
        toolButton_n->setObjectName(QString::fromUtf8("toolButton_n"));
//        toolButton_n->setGeometry(QRect(236+7*KETBOARD_H, 101+4*KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_n->setGeometry(QRect(153+7*KETBOARD_H, 76+4*KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_n->sizePolicy().hasHeightForWidth());
        toolButton_n->setSizePolicy(sizePolicy);
        toolButton_n->setFocusPolicy(Qt::NoFocus);
        toolButton_c = new QToolButton(KeyBoard);
        toolButton_c->setObjectName(QString::fromUtf8("toolButton_c"));
//        toolButton_c->setGeometry(QRect(149+4*KETBOARD_H, 101+4*KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_c->setGeometry(QRect(97+4*KETBOARD_H, 76+4*KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_c->sizePolicy().hasHeightForWidth());
        toolButton_c->setSizePolicy(sizePolicy);
        toolButton_c->setFocusPolicy(Qt::NoFocus);
        toolButton_x = new QToolButton(KeyBoard);
        toolButton_x->setObjectName(QString::fromUtf8("toolButton_x"));
//        toolButton_x->setGeometry(QRect(120+3*KETBOARD_H, 101+4*KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_x->setGeometry(QRect(78+3*KETBOARD_H, 76+4*KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_x->sizePolicy().hasHeightForWidth());
        toolButton_x->setSizePolicy(sizePolicy);
        toolButton_x->setFocusPolicy(Qt::NoFocus);
        toolButton_up = new QToolButton(KeyBoard);
        toolButton_up->setObjectName(QString::fromUtf8("toolButton_up"));
//        toolButton_up->setGeometry(QRect(294+9*KETBOARD_H, 101+4*KEYBOARD_W, 38+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_up->setGeometry(QRect(191+9*KETBOARD_H, 76+4*KEYBOARD_W, 24+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_up->sizePolicy().hasHeightForWidth());
        toolButton_up->setSizePolicy(sizePolicy);
        toolButton_up->setFocusPolicy(Qt::NoFocus);
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/new/keypad/picture/keypad/top.png"), QSize(), QIcon::Normal, QIcon::Off);
        toolButton_up->setIcon(icon2);
        toolButton_backspace = new QToolButton(KeyBoard);
        toolButton_backspace->setObjectName(QString::fromUtf8("toolButton_backspace"));
//        toolButton_backspace->setGeometry(QRect(339+11*KETBOARD_H, 26+KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_backspace->setGeometry(QRect(220+11*KETBOARD_H, 20+KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_backspace->sizePolicy().hasHeightForWidth());
        toolButton_backspace->setSizePolicy(sizePolicy);
        toolButton_backspace->setFocusPolicy(Qt::NoFocus);
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/new/keypad/picture/keypad/backspace.png"), QSize(), QIcon::Normal, QIcon::Off);
        toolButton_backspace->setIcon(icon3);
        toolButton_5 = new QToolButton(KeyBoard);
        toolButton_5->setObjectName(QString::fromUtf8("toolButton_5"));
//        toolButton_5->setGeometry(QRect(163+5*KETBOARD_H, 26+KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_5->setGeometry(QRect(106+5*KETBOARD_H, 20+KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_5->sizePolicy().hasHeightForWidth());
        toolButton_5->setSizePolicy(sizePolicy);
        toolButton_5->setFocusPolicy(Qt::NoFocus);
        toolButton_v = new QToolButton(KeyBoard);
        toolButton_v->setObjectName(QString::fromUtf8("toolButton_v"));
//        toolButton_v->setGeometry(QRect(178+5*KETBOARD_H, 101+4*KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_v->setGeometry(QRect(116+5*KETBOARD_H, 76+4*KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_v->sizePolicy().hasHeightForWidth());
        toolButton_v->setSizePolicy(sizePolicy);
        toolButton_v->setFocusPolicy(Qt::NoFocus);
        toolButton_esc = new QToolButton(KeyBoard);
        toolButton_esc->setObjectName(QString::fromUtf8("toolButton_esc"));
        toolButton_esc->setStyleSheet("background-color:rgb(199,237,204)");
//        toolButton_esc->setGeometry(QRect(8, -1, 37+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_esc->setGeometry(QRect(5, -1, 24+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_esc->sizePolicy().hasHeightForWidth());
        toolButton_esc->setSizePolicy(sizePolicy);
        toolButton_esc->setFocusPolicy(Qt::NoFocus);
        toolButton_enter = new QToolButton(KeyBoard);
        toolButton_enter->setObjectName(QString::fromUtf8("toolButton_enter"));
        toolButton_enter->setStyleSheet("background-color:rgb(199,237,204)");
//        toolButton_enter->setGeometry(QRect(308+6*KETBOARD_H, 0, 61+6*KETBOARD_H, 25+KEYBOARD_W));
        toolButton_enter->setGeometry(QRect(200+6*KETBOARD_H, 0, 40+6*KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_enter->sizePolicy().hasHeightForWidth());
        toolButton_enter->setSizePolicy(sizePolicy);
        toolButton_enter->setFocusPolicy(Qt::NoFocus);
        toolButton_p = new QToolButton(KeyBoard);
        toolButton_p->setObjectName(QString::fromUtf8("toolButton_p"));
//        toolButton_p->setGeometry(QRect(313+10*KETBOARD_H, 51+2*KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_p->setGeometry(QRect(203+10*KETBOARD_H, 39+2*KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_p->sizePolicy().hasHeightForWidth());
        toolButton_p->setSizePolicy(sizePolicy);
        toolButton_p->setFocusPolicy(Qt::NoFocus);
        toolButton_down = new QToolButton(KeyBoard);
        toolButton_down->setObjectName(QString::fromUtf8("toolButton_down"));
//        toolButton_down->setGeometry(QRect(294+9*KETBOARD_H, 126+5*KEYBOARD_W, 38+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_down->setGeometry(QRect(191+9*KETBOARD_H, 95+5*KEYBOARD_W, 24+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_down->sizePolicy().hasHeightForWidth());
        toolButton_down->setSizePolicy(sizePolicy);
        toolButton_down->setFocusPolicy(Qt::NoFocus);
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/new/keypad/picture/keypad/down.png"), QSize(), QIcon::Normal, QIcon::Off);
        toolButton_down->setIcon(icon4);
        toolButton_4 = new QToolButton(KeyBoard);
        toolButton_4->setObjectName(QString::fromUtf8("toolButton_4"));
//        toolButton_4->setGeometry(QRect(134+4*KETBOARD_H, 26+KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_4->setGeometry(QRect(87+4*KETBOARD_H, 20+KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_4->sizePolicy().hasHeightForWidth());
        toolButton_4->setSizePolicy(sizePolicy);
        toolButton_4->setFocusPolicy(Qt::NoFocus);
        toolButton_q = new QToolButton(KeyBoard);
        toolButton_q->setObjectName(QString::fromUtf8("toolButton_q"));
//        toolButton_q->setGeometry(QRect(54+KETBOARD_H, 50+2*KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_q->setGeometry(QRect(35+KETBOARD_H, 39+2*KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_q->sizePolicy().hasHeightForWidth());
        toolButton_q->setSizePolicy(sizePolicy);
        toolButton_q->setFocusPolicy(Qt::NoFocus);
        toolButton_0 = new QToolButton(KeyBoard);
        toolButton_0->setObjectName(QString::fromUtf8("toolButton_0"));
//        toolButton_0->setGeometry(QRect(309+10*KETBOARD_H, 26+KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_0->setGeometry(QRect(200+10*KETBOARD_H, 20+KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_0->sizePolicy().hasHeightForWidth());
        toolButton_0->setSizePolicy(sizePolicy);
        toolButton_0->setFocusPolicy(Qt::NoFocus);
        toolButton_f = new QToolButton(KeyBoard);
        toolButton_f->setObjectName(QString::fromUtf8("toolButton_f"));
//        toolButton_f->setGeometry(QRect(158+5*KETBOARD_H, 76+3*KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_f->setGeometry(QRect(102+5*KETBOARD_H, 57+3*KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_f->sizePolicy().hasHeightForWidth());
        toolButton_f->setSizePolicy(sizePolicy);
        toolButton_f->setFocusPolicy(Qt::NoFocus);
        toolButton_space = new QToolButton(KeyBoard);
        toolButton_space->setObjectName(QString::fromUtf8("toolButton_space"));
//        toolButton_space->setGeometry(QRect(120+KETBOARD_H, 126+5*KEYBOARD_W, 131+7*KETBOARD_H, 25+KEYBOARD_W));
        toolButton_space->setGeometry(QRect(78+KETBOARD_H, 95+5*KEYBOARD_W, 85+7*KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_space->sizePolicy().hasHeightForWidth());
        toolButton_space->setSizePolicy(sizePolicy);
        toolButton_space->setFocusPolicy(Qt::NoFocus);
        toolButton_wenhao = new QToolButton(KeyBoard);
        toolButton_wenhao->setObjectName(QString::fromUtf8("toolButton_wenhao"));
        toolButton_wenhao->setStyleSheet("background-color:rgb(199,237,204)");
//        toolButton_wenhao->setGeometry(QRect(39+KETBOARD_H, 75+3*KEYBOARD_W, 33+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_wenhao->setGeometry(QRect(25+KETBOARD_H, 57+3*KEYBOARD_W, 22+KETBOARD_H, 19+KEYBOARD_W));
        toolButton_e = new QToolButton(KeyBoard);
        toolButton_e->setObjectName(QString::fromUtf8("toolButton_e"));
//        toolButton_e->setGeometry(QRect(113+3*KETBOARD_H, 51+2*KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_e->setGeometry(QRect(73+3*KETBOARD_H, 39+2*KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_e->sizePolicy().hasHeightForWidth());
        toolButton_e->setSizePolicy(sizePolicy);
        toolButton_e->setFocusPolicy(Qt::NoFocus);
        horizontalSlider = new QSlider(KeyBoard);
        horizontalSlider->setObjectName(QString::fromUtf8("horizontalSlider"));
//        horizontalSlider->setGeometry(QRect(6, 128+5*KEYBOARD_W, 111, 20+KEYBOARD_W));
        horizontalSlider->setGeometry(QRect(4, 97+5*KEYBOARD_W, 72, 15+KEYBOARD_W));
        horizontalSlider->setFocusPolicy(Qt::NoFocus);
        horizontalSlider->setAcceptDrops(false);
        horizontalSlider->setLayoutDirection(Qt::LeftToRight);
        horizontalSlider->setAutoFillBackground(false);
        horizontalSlider->setMaximum(255);
        horizontalSlider->setMinimum(100);
        horizontalSlider->setValue(255);
        horizontalSlider->setSliderPosition(255);
        horizontalSlider->setOrientation(Qt::Horizontal);
        horizontalSlider->setTickPosition(QSlider::NoTicks);
        toolButton_2 = new QToolButton(KeyBoard);
        toolButton_2->setObjectName(QString::fromUtf8("toolButton_2"));
//        toolButton_2->setGeometry(QRect(76+2*KETBOARD_H, 26+KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_2->setGeometry(QRect(49+2*KETBOARD_H, 20+KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_2->sizePolicy().hasHeightForWidth());
        toolButton_2->setSizePolicy(sizePolicy);
        toolButton_2->setFocusPolicy(Qt::NoFocus);
        toolButton_1 = new QToolButton(KeyBoard);
        toolButton_1->setObjectName(QString::fromUtf8("toolButton_1"));
//        toolButton_1->setGeometry(QRect(46+KETBOARD_H, 26+KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_1->setGeometry(QRect(30+KETBOARD_H, 20+KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_1->sizePolicy().hasHeightForWidth());
        toolButton_1->setSizePolicy(sizePolicy);
        toolButton_1->setFocusPolicy(Qt::NoFocus);
        toolButton_1->setContextMenuPolicy(Qt::DefaultContextMenu);
        toolButton_1->setLayoutDirection(Qt::LeftToRight);
        toolButton_1->setPopupMode(QToolButton::DelayedPopup);
        toolButton_1->setAutoRaise(false);
        toolButton_1->setArrowType(Qt::NoArrow);
        toolButton_z = new QToolButton(KeyBoard);
        toolButton_z->setObjectName(QString::fromUtf8("toolButton_z"));
//        toolButton_z->setGeometry(QRect(90+2*KETBOARD_H, 100+4*KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
         toolButton_z->setGeometry(QRect(58+2*KETBOARD_H, 75+4*KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_z->sizePolicy().hasHeightForWidth());
        toolButton_z->setSizePolicy(sizePolicy);
        toolButton_z->setFocusPolicy(Qt::NoFocus);
        toolButton_Inv = new QToolButton(KeyBoard);
        toolButton_Inv->setObjectName(QString::fromUtf8("toolButton_Inv"));
        toolButton_Inv->setStyleSheet("background-color:rgb(199,237,204)");
//        toolButton_Inv->setGeometry(QRect(270+5*KETBOARD_H, 0, 33+2*KETBOARD_H, 25+KEYBOARD_W));
        toolButton_Inv->setGeometry(QRect(175+5*KETBOARD_H, 0, 22+2*KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_Inv->sizePolicy().hasHeightForWidth());
        toolButton_Inv->setSizePolicy(sizePolicy);
        toolButton_Inv->setFocusPolicy(Qt::NoFocus);
        toolButton_line3 = new QToolButton(KeyBoard);
        toolButton_line3->setObjectName(QString::fromUtf8("toolButton_line3"));
        toolButton_line3->setStyleSheet("background-color:rgb(199,237,204)");
//        toolButton_line3->setGeometry(QRect(60+KETBOARD_H, 100+4*KEYBOARD_W, 30+KETBOARD_H, 25+KEYBOARD_W));
        toolButton_line3->setGeometry(QRect(39+KETBOARD_H, 75+4*KEYBOARD_W, 20+KETBOARD_H, 19+KEYBOARD_W));
        sizePolicy.setHeightForWidth(toolButton_line3->sizePolicy().hasHeightForWidth());
        toolButton_line3->setSizePolicy(sizePolicy);
        toolButton_line3->setFocusPolicy(Qt::NoFocus);

        retranslateUi(KeyBoard);

        QMetaObject::connectSlotsByName(KeyBoard);
    } // setupUi

    void retranslateUi(QDialog *KeyBoard)
    {
        KeyBoard->setWindowTitle(QApplication::translate("KeyBoard", "Dialog", 0, QApplication::UnicodeUTF8));
        toolButton_l->setText(QApplication::translate("KeyBoard", "l", 0, QApplication::UnicodeUTF8));
        toolButton_line2->setText(QApplication::translate("KeyBoard", "\\", 0, QApplication::UnicodeUTF8));
        toolButton_line1->setText(QApplication::translate("KeyBoard", "/", 0, QApplication::UnicodeUTF8));
        toolButton_m->setText(QApplication::translate("KeyBoard", "m", 0, QApplication::UnicodeUTF8));
        toolButton_right->setText(QString());
        toolButton_j->setText(QApplication::translate("KeyBoard", "j", 0, QApplication::UnicodeUTF8));
        toolButton_k->setText(QApplication::translate("KeyBoard", "k", 0, QApplication::UnicodeUTF8));
        toolButton_h->setText(QApplication::translate("KeyBoard", "h", 0, QApplication::UnicodeUTF8));
        toolButton_9->setText(QApplication::translate("KeyBoard", "9", 0, QApplication::UnicodeUTF8));
        toolButton_r->setText(QApplication::translate("KeyBoard", "r", 0, QApplication::UnicodeUTF8));
        toolButton_8->setText(QApplication::translate("KeyBoard", "8", 0, QApplication::UnicodeUTF8));
        toolButton_t->setText(QApplication::translate("KeyBoard", "t", 0, QApplication::UnicodeUTF8));
        toolButton_7->setText(QApplication::translate("KeyBoard", "7", 0, QApplication::UnicodeUTF8));
        toolButton_u->setText(QApplication::translate("KeyBoard", "u", 0, QApplication::UnicodeUTF8));
        toolButton_d->setText(QApplication::translate("KeyBoard", "d", 0, QApplication::UnicodeUTF8));
        toolButton_3->setText(QApplication::translate("KeyBoard", "3", 0, QApplication::UnicodeUTF8));
        toolButton_tab->setText(QApplication::translate("KeyBoard", "T", 0, QApplication::UnicodeUTF8));
        toolButton_6->setText(QApplication::translate("KeyBoard", "6", 0, QApplication::UnicodeUTF8));
        toolButton_y->setText(QApplication::translate("KeyBoard", "y", 0, QApplication::UnicodeUTF8));
        toolButton_dot->setText(QApplication::translate("KeyBoard", ".", 0, QApplication::UnicodeUTF8));
        toolButton_g->setText(QApplication::translate("KeyBoard", "g", 0, QApplication::UnicodeUTF8));
        toolButton_i->setText(QApplication::translate("KeyBoard", "i", 0, QApplication::UnicodeUTF8));
        toolButton_s->setText(QApplication::translate("KeyBoard", "s", 0, QApplication::UnicodeUTF8));
        toolButton_o->setText(QApplication::translate("KeyBoard", "o", 0, QApplication::UnicodeUTF8));
        toolButton_w->setText(QApplication::translate("KeyBoard", "w", 0, QApplication::UnicodeUTF8));
        toolButton_a->setText(QApplication::translate("KeyBoard", "a", 0, QApplication::UnicodeUTF8));
        toolButton_capslock->setText(QApplication::translate("KeyBoard", "C", 0, QApplication::UnicodeUTF8));
        toolButton_b->setText(QApplication::translate("KeyBoard", "b", 0, QApplication::UnicodeUTF8));
        toolButton_left->setText(QString());
        toolButton_n->setText(QApplication::translate("KeyBoard", "n", 0, QApplication::UnicodeUTF8));
        toolButton_c->setText(QApplication::translate("KeyBoard", "c", 0, QApplication::UnicodeUTF8));
        toolButton_x->setText(QApplication::translate("KeyBoard", "x", 0, QApplication::UnicodeUTF8));
        toolButton_up->setText(QString());
        toolButton_backspace->setText(QString());
        toolButton_5->setText(QApplication::translate("KeyBoard", "5", 0, QApplication::UnicodeUTF8));
        toolButton_v->setText(QApplication::translate("KeyBoard", "v", 0, QApplication::UnicodeUTF8));
        toolButton_esc->setText(QApplication::translate("KeyBoard", "Es", 0, QApplication::UnicodeUTF8));
        toolButton_enter->setText(QApplication::translate("KeyBoard", "Ent", 0, QApplication::UnicodeUTF8));
        toolButton_p->setText(QApplication::translate("KeyBoard", "p", 0, QApplication::UnicodeUTF8));
        toolButton_down->setText(QString());
        toolButton_4->setText(QApplication::translate("KeyBoard", "4", 0, QApplication::UnicodeUTF8));
        toolButton_q->setText(QApplication::translate("KeyBoard", "q", 0, QApplication::UnicodeUTF8));
        toolButton_0->setText(QApplication::translate("KeyBoard", "0", 0, QApplication::UnicodeUTF8));
        toolButton_f->setText(QApplication::translate("KeyBoard", "f", 0, QApplication::UnicodeUTF8));
        toolButton_space->setText(QString());
        toolButton_wenhao->setText(QApplication::translate("KeyBoard", "?", 0, QApplication::UnicodeUTF8));
        toolButton_e->setText(QApplication::translate("KeyBoard", "e", 0, QApplication::UnicodeUTF8));
        toolButton_2->setText(QApplication::translate("KeyBoard", "2", 0, QApplication::UnicodeUTF8));
        toolButton_1->setText(QApplication::translate("KeyBoard", "1", 0, QApplication::UnicodeUTF8));
        toolButton_z->setText(QApplication::translate("KeyBoard", "z", 0, QApplication::UnicodeUTF8));
        toolButton_Inv->setText(QApplication::translate("KeyBoard", "In", 0, QApplication::UnicodeUTF8));
        toolButton_line3->setText(QApplication::translate("KeyBoard", ",", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class KeyBoard: public Ui_KeyBoard {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_KEYBOARD_H
